;this file for FamiTone2 library generated by text2data tool

TestMusic_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c6,$cf,$cb,$c9,$c7,$c6,$c5,$c4,$00,$07
@env2:
	.byte $c3,$c6,$c5,$c4,$c3,$c2,$c1,$c1,$00,$07


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$1a,$9d,$00,$85,$1a,$85,$1f,$29,$00,$85,$1a,$9d,$00,$85,$1a
	.byte $85,$1f,$29,$00,$85
@ref1:
	.byte $1a,$9d,$00,$85,$1a,$85,$1f,$29,$00,$85,$1a,$9d,$00,$85,$1a,$85
	.byte $1f,$29,$00,$85
	.byte $ff,$14
	.word @ref1
	.byte $ff,$14
	.word @ref1
	.byte $ff,$14
	.word @ref1
	.byte $ff,$14
	.word @ref1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref6:
	.byte $00,$f9,$83
@ref7:
	.byte $00,$f9,$83
@ref8:
	.byte $80,$02,$9d,$00,$85,$0a,$95,$0c,$9d,$11,$1b,$29,$11,$1b,$28,$89
@ref9:
	.byte $02,$9d,$00,$85,$0a,$95,$0c,$9d,$11,$1b,$29,$11,$1b,$28,$89
	.byte $ff,$0f
	.word @ref9
	.byte $ff,$0f
	.word @ref9
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref12:
	.byte $01,$80,$59,$01,$59,$01,$59,$01,$59,$01,$59,$01,$59,$01,$55,$01
	.byte $53,$01,$59,$01,$59,$01,$59,$01,$59,$01,$55,$01,$53,$01,$4f,$01
	.byte $4a,$81
@ref13:
	.byte $01,$59,$01,$59,$01,$59,$01,$59,$01,$59,$01,$59,$01,$55,$01,$53
	.byte $01,$59,$01,$59,$01,$59,$01,$59,$01,$55,$01,$53,$01,$4f,$01,$4a
	.byte $81
	.byte $ff,$21
	.word @ref13
	.byte $ff,$21
	.word @ref13
@ref16:
	.byte $60,$62,$87,$4b,$01,$4b,$01,$60,$62,$83,$5d,$01,$59,$01,$55,$01
	.byte $60,$62,$8b,$4b,$01,$4b,$01,$60,$62,$83,$59,$01,$55,$01,$52,$85
	.byte $00,$81
	.byte $ff,$22
	.word @ref16
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref18:
	.byte $82,$21,$00,$85,$0b,$00,$85,$21,$01,$21,$0b,$01,$0b,$01,$17,$01
	.byte $17,$21,$00,$85,$0b,$00,$85,$21,$01,$21,$0b,$01,$0b,$01,$17,$01
	.byte $16,$81
@ref19:
	.byte $21,$00,$85,$0b,$00,$85,$21,$01,$21,$0b,$01,$0b,$01,$17,$01,$17
	.byte $21,$00,$85,$0b,$00,$85,$21,$01,$21,$0b,$01,$0b,$01,$17,$01,$16
	.byte $81
	.byte $ff,$21
	.word @ref19
	.byte $ff,$21
	.word @ref19
	.byte $ff,$21
	.word @ref19
	.byte $ff,$21
	.word @ref19
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref24:
	.byte $f9,$85
@ref25:
	.byte $f9,$85
@ref26:
	.byte $f9,$85
@ref27:
	.byte $f9,$85
@ref28:
	.byte $f9,$85
@ref29:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@ref30:
	.byte $82,$33,$37,$80,$41,$82,$33,$37,$80,$40,$85,$82,$30,$85,$37,$80
	.byte $41,$82,$33,$37,$80,$40,$89
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
@song1ch0loop:
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $ff,$0f
	.word @ref30
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@ref46:
	.byte $bf
@ref47:
	.byte $bf
@ref48:
	.byte $bf
@ref49:
	.byte $bf
@ref50:
	.byte $80,$02,$ad,$0a,$8d
@ref51:
	.byte $02,$00,$82,$02,$00,$80,$02,$00,$82,$02,$00,$80,$02,$00,$82,$02
	.byte $00,$83,$80,$06,$00,$83,$06,$00,$82,$06,$00,$80,$07,$01,$0a,$89
@ref52:
	.byte $02,$ad,$0a,$8d
	.byte $ff,$18
	.word @ref51
@song1ch1loop:
	.byte $ff,$04
	.word @ref50
	.byte $ff,$18
	.word @ref51
@ref56:
	.byte $02,$ad,$0a,$8d
	.byte $ff,$18
	.word @ref51
@ref58:
	.byte $02,$ad,$0a,$8d
	.byte $ff,$18
	.word @ref51
@ref60:
	.byte $bf
@ref61:
	.byte $bf
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@ref62:
	.byte $bf
@ref63:
	.byte $bf
@ref64:
	.byte $bf
@ref65:
	.byte $bf
@ref66:
	.byte $bf
@ref67:
	.byte $bf
@ref68:
	.byte $bf
@ref69:
	.byte $bf
@song1ch2loop:
@ref70:
	.byte $82,$4a,$4e,$4a,$a9,$4a,$4e,$4a,$85,$40,$81
@ref71:
	.byte $87,$3c,$3a,$40,$b1
@ref72:
	.byte $4a,$4e,$4a,$a9,$4a,$4e,$4a,$85,$40,$81
	.byte $ff,$05
	.word @ref71
@ref74:
	.byte $4a,$4e,$58,$a9,$4a,$4e,$58,$85,$52,$81
@ref75:
	.byte $01,$52,$85,$4f,$52,$ad
	.byte $ff,$0a
	.word @ref74
	.byte $ff,$06
	.word @ref75
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@ref78:
	.byte $00,$bd
@ref79:
	.byte $bf
@ref80:
	.byte $82,$17,$17,$16,$85,$17,$80,$13,$01,$82,$16,$85,$17,$16,$85,$17
	.byte $80,$13,$01,$82,$12,$81
@ref81:
	.byte $17,$17,$16,$85,$17,$80,$13,$01,$82,$16,$85,$17,$16,$85,$17,$80
	.byte $13,$01,$82,$12,$81
	.byte $ff,$11
	.word @ref81
	.byte $ff,$11
	.word @ref81
	.byte $ff,$11
	.word @ref81
	.byte $ff,$11
	.word @ref81
@song1ch3loop:
	.byte $ff,$11
	.word @ref80
	.byte $ff,$11
	.word @ref81
	.byte $ff,$11
	.word @ref81
	.byte $ff,$11
	.word @ref81
	.byte $ff,$11
	.word @ref81
	.byte $ff,$11
	.word @ref81
@ref92:
	.byte $00,$bd
@ref93:
	.byte $bf
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
@ref100:
	.byte $bf
@ref101:
	.byte $bf
@song1ch4loop:
@ref102:
	.byte $bf
@ref103:
	.byte $bf
@ref104:
	.byte $bf
@ref105:
	.byte $bf
@ref106:
	.byte $bf
@ref107:
	.byte $bf
@ref108:
	.byte $bf
@ref109:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
