;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @sfx_ntsc_0,@sfx_pal_0
	.word @sfx_ntsc_1,@sfx_pal_1
	.word @sfx_ntsc_2,@sfx_pal_2

@sfx_ntsc_0:
	.byte $80,$bf,$81,$ab,$82,$01,$02,$81,$93,$02,$81,$67,$01,$81,$2d,$00
@sfx_ntsc_1:
	.byte $80,$bf,$81,$54,$82,$00,$04,$81,$6a,$04,$81,$42,$00
@sfx_ntsc_2:
	.byte $89,$3f,$8a,$0d,$01,$89,$3e,$01,$89,$3a,$00
@sfx_pal_0:
	.byte $80,$bf,$81,$8c,$82,$01,$02,$81,$76,$02,$81,$4d,$01,$81,$18,$00
@sfx_pal_1:
	.byte $80,$bf,$81,$4e,$82,$00,$04,$81,$62,$04,$81,$3e,$00
@sfx_pal_2:
	.byte $89,$3f,$8a,$0d,$01,$89,$3e,$01,$89,$3a,$00
