;this file for FamiTone2 library generated by text2data tool

DMCmusic_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00

@samples:
	.byte $00+FT_DPCM_PTR,$00,$00	;1
	.byte $00+FT_DPCM_PTR,$00,$00	;2
	.byte $00+FT_DPCM_PTR,$00,$00	;3
	.byte $00+FT_DPCM_PTR,$00,$00	;4
	.byte $00+FT_DPCM_PTR,$00,$00	;5
	.byte $00+FT_DPCM_PTR,$00,$00	;6
	.byte $00+FT_DPCM_PTR,$00,$00	;7
	.byte $00+FT_DPCM_PTR,$00,$00	;8
	.byte $00+FT_DPCM_PTR,$00,$00	;9
	.byte $00+FT_DPCM_PTR,$00,$00	;10
	.byte $00+FT_DPCM_PTR,$00,$00	;11
	.byte $00+FT_DPCM_PTR,$00,$00	;12
	.byte $00+FT_DPCM_PTR,$00,$00	;13
	.byte $00+FT_DPCM_PTR,$00,$00	;14
	.byte $00+FT_DPCM_PTR,$00,$00	;15
	.byte $00+FT_DPCM_PTR,$00,$00	;16
	.byte $00+FT_DPCM_PTR,$00,$00	;17
	.byte $00+FT_DPCM_PTR,$00,$00	;18
	.byte $00+FT_DPCM_PTR,$00,$00	;19
	.byte $00+FT_DPCM_PTR,$00,$00	;20
	.byte $00+FT_DPCM_PTR,$00,$00	;21
	.byte $00+FT_DPCM_PTR,$00,$00	;22
	.byte $00+FT_DPCM_PTR,$00,$00	;23
	.byte $00+FT_DPCM_PTR,$00,$00	;24
	.byte $00+FT_DPCM_PTR,$36,$0f	;25
	.byte $00+FT_DPCM_PTR,$00,$00	;26
	.byte $0e+FT_DPCM_PTR,$3f,$0f	;27
	.byte $00+FT_DPCM_PTR,$00,$00	;28
	.byte $1e+FT_DPCM_PTR,$38,$0f	;29
	.byte $2d+FT_DPCM_PTR,$30,$0f	;30
	.byte $00+FT_DPCM_PTR,$00,$00	;31
	.byte $00+FT_DPCM_PTR,$00,$00	;32
	.byte $00+FT_DPCM_PTR,$00,$00	;33
	.byte $00+FT_DPCM_PTR,$00,$00	;34
	.byte $00+FT_DPCM_PTR,$00,$00	;35
	.byte $00+FT_DPCM_PTR,$00,$00	;36
	.byte $00+FT_DPCM_PTR,$00,$00	;37
	.byte $00+FT_DPCM_PTR,$00,$00	;38
	.byte $00+FT_DPCM_PTR,$00,$00	;39
	.byte $00+FT_DPCM_PTR,$00,$00	;40
	.byte $00+FT_DPCM_PTR,$00,$00	;41
	.byte $00+FT_DPCM_PTR,$00,$00	;42
	.byte $00+FT_DPCM_PTR,$00,$00	;43
	.byte $00+FT_DPCM_PTR,$00,$00	;44
	.byte $00+FT_DPCM_PTR,$00,$00	;45
	.byte $00+FT_DPCM_PTR,$00,$00	;46
	.byte $00+FT_DPCM_PTR,$00,$00	;47
	.byte $00+FT_DPCM_PTR,$00,$00	;48
	.byte $00+FT_DPCM_PTR,$00,$00	;49
	.byte $00+FT_DPCM_PTR,$00,$00	;50
	.byte $00+FT_DPCM_PTR,$00,$00	;51
	.byte $00+FT_DPCM_PTR,$00,$00	;52
	.byte $00+FT_DPCM_PTR,$00,$00	;53
	.byte $00+FT_DPCM_PTR,$00,$00	;54
	.byte $00+FT_DPCM_PTR,$00,$00	;55
	.byte $00+FT_DPCM_PTR,$00,$00	;56
	.byte $00+FT_DPCM_PTR,$00,$00	;57
	.byte $00+FT_DPCM_PTR,$00,$00	;58
	.byte $00+FT_DPCM_PTR,$00,$00	;59
	.byte $00+FT_DPCM_PTR,$00,$00	;60
	.byte $00+FT_DPCM_PTR,$00,$00	;61
	.byte $00+FT_DPCM_PTR,$00,$00	;62
	.byte $00+FT_DPCM_PTR,$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c5,$ca,$c8,$c6,$c4,$00,$04
@env2:
	.byte $c3,$c6,$c5,$c3,$c2,$00,$04


@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $00,$f9,$83
@ref1:
	.byte $82,$0c,$b5,$10,$85,$02,$bd
@ref2:
	.byte $0c,$b5,$10,$85,$02,$bd
@song0ch0loop:
	.byte $ff,$06
	.word @ref1
	.byte $ff,$06
	.word @ref2
	.byte $ff,$06
	.word @ref2
	.byte $ff,$06
	.word @ref2
	.byte $ff,$06
	.word @ref2
	.byte $ff,$06
	.word @ref2
@ref9:
	.byte $00,$f9,$83
@ref10:
	.byte $00,$f9,$83
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref11:
	.byte $00,$f9,$83
@ref12:
	.byte $00,$f9,$83
@ref13:
	.byte $00,$f9,$83
@song0ch1loop:
@ref14:
	.byte $84,$63,$00,$99,$53,$00,$97,$54,$59,$00,$89,$4b,$00,$89,$4b,$00
	.byte $89,$4b,$00,$89
@ref15:
	.byte $63,$00,$99,$53,$00,$97,$54,$59,$00,$89,$4b,$00,$89,$4b,$00,$89
	.byte $4b,$00,$89
@ref16:
	.byte $4b,$53,$59,$4b,$53,$59,$4b,$53,$59,$4b,$53,$59,$55,$53,$4f,$53
	.byte $4b,$4f,$53,$4b,$4f,$53,$4b,$4f,$52,$85,$58,$85,$54,$85,$52,$85
	.byte $ff,$20
	.word @ref16
@ref18:
	.byte $4b,$63,$5d,$67,$4b,$63,$5d,$6b,$67,$63,$61,$63,$5d,$4b,$4b,$4b
	.byte $61,$4f,$4f,$4f,$4b,$63,$5d,$67,$4b,$63,$5d,$67,$6b,$67,$63,$60
	.byte $81
	.byte $ff,$21
	.word @ref18
	.byte $ff,$13
	.word @ref15
	.byte $ff,$13
	.word @ref15
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref22:
	.byte $00,$f9,$83
@ref23:
	.byte $00,$f9,$83
@ref24:
	.byte $00,$f9,$83
@song0ch2loop:
@ref25:
	.byte $82,$4a,$89,$4f,$4a,$9d,$44,$8d,$41,$32,$99,$36,$85,$3a,$85,$3c
	.byte $85,$40,$85
@ref26:
	.byte $4a,$89,$4f,$4a,$9d,$44,$8d,$41,$32,$99,$36,$85,$3a,$85,$3c,$85
	.byte $40,$85
	.byte $ff,$12
	.word @ref26
	.byte $ff,$12
	.word @ref26
	.byte $ff,$12
	.word @ref26
	.byte $ff,$12
	.word @ref26
	.byte $ff,$12
	.word @ref26
	.byte $ff,$12
	.word @ref26
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref33:
	.byte $f9,$85
@ref34:
	.byte $f9,$85
@ref35:
	.byte $f9,$85
@song0ch3loop:
@ref36:
	.byte $f9,$85
@ref37:
	.byte $f9,$85
@ref38:
	.byte $f9,$85
@ref39:
	.byte $f9,$85
@ref40:
	.byte $f9,$85
@ref41:
	.byte $f9,$85
@ref42:
	.byte $f9,$85
@ref43:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref44:
	.byte $3a,$85,$32,$83,$3b,$37,$3a,$32,$85,$3a,$85,$32,$83,$3b,$37,$3a
	.byte $33,$33,$3a,$85,$32,$83,$3b,$37,$3a,$32,$85,$3a,$85,$32,$83,$3d
	.byte $3d,$3d,$3c,$36,$32
	.byte $ff,$25
	.word @ref44
	.byte $ff,$25
	.word @ref44
@song0ch4loop:
	.byte $ff,$25
	.word @ref44
	.byte $ff,$25
	.word @ref44
	.byte $ff,$25
	.word @ref44
	.byte $ff,$25
	.word @ref44
	.byte $ff,$25
	.word @ref44
	.byte $ff,$25
	.word @ref44
	.byte $ff,$25
	.word @ref44
	.byte $ff,$25
	.word @ref44
	.byte $fd
	.word @song0ch4loop
