;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @sfx_ntsc_0,@sfx_pal_0

@sfx_ntsc_0:
	.byte $80,$bf,$81,$ab,$82,$01,$02,$81,$93,$02,$81,$67,$01,$81,$2d,$00
@sfx_pal_0:
	.byte $80,$bf,$81,$8c,$82,$01,$02,$81,$76,$02,$81,$4d,$01,$81,$18,$00
