;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @sfx_ntsc_0,@sfx_pal_0
	.word @sfx_ntsc_1,@sfx_pal_1
	.word @sfx_ntsc_2,@sfx_pal_2
	.word @sfx_ntsc_3,@sfx_pal_3
	.word @sfx_ntsc_4,@sfx_pal_4
	
; moved the labels, to save space

@sfx_ntsc_0:
@sfx_pal_0:
	.byte $89,$39,$8a,$85,$01,$89,$38,$8a,$86,$01,$89,$37,$8a,$87,$01,$89 ; i edited the volume softer, the 3x numbers
	.byte $36,$8a,$88,$01,$89,$35,$8a,$89,$01,$89,$34,$8a,$8a,$01,$89,$33
	.byte $8a,$8b,$02,$89,$32,$02,$89,$31,$01,$89,$31,$02,$89,$31,$02,$89
	.byte $30,$00
	
;	.byte $89,$3b,$8a,$85,$01,$89,$3a,$8a,$86,$01,$89,$39,$8a,$87,$01,$89
;	.byte $38,$8a,$88,$01,$89,$37,$8a,$89,$01,$89,$36,$8a,$8a,$01,$89,$35
;	.byte $8a,$8b,$02,$89,$34,$02,$89,$33,$01,$89,$32,$02,$89,$31,$02,$89
;	.byte $30,$00
@sfx_ntsc_1:
@sfx_pal_1:
	.byte $89,$36,$8a,$8a,$04,$89,$35,$02,$89,$36,$8a,$89,$04,$89,$35,$02
	.byte $89,$36,$8a,$88,$04,$89,$35,$02,$89,$34,$02,$89,$33,$01,$89,$31
	.byte $01,$89,$30,$00
@sfx_ntsc_2:
@sfx_pal_2:
	.byte $89,$3d,$8a,$0e,$01,$89,$3c,$01,$89,$3b,$01,$89,$3a,$01,$89,$38
	.byte $01,$89,$36,$01,$89,$34,$01,$89,$32,$1d,$89,$30,$00
@sfx_ntsc_3:
@sfx_pal_3:
	.byte $89,$3f,$8a,$0e,$0c,$8a,$0f,$0c,$8a,$0e,$0c,$8a,$0f,$0c,$8a,$0e ; i edited one volume, louder
	.byte $0c,$8a,$0f,$0c,$8a,$0e,$00
;	.byte $89,$3d,$8a,$0e,$0c,$8a,$0f,$0c,$8a,$0e,$0c,$8a,$0f,$0c,$8a,$0e
;	.byte $0c,$8a,$0f,$0c,$8a,$0e,$00
@sfx_ntsc_4:
@sfx_pal_4:
	.byte 0 ;silence
	

