;this file for FamiTone2 library generated by text2data tool

SpacyMusic_music_data:
	.byte 5
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env3,@env0,@env5
	.byte $00
	.byte $b0 ;instrument $04
	.word @env2,@env0,@env6
	.byte $00
	.byte $b0 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $06
	.word @env4,@env0,@env7
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$ce,$cc,$ca,$c8,$c6,$00,$05
@env2:
	.byte $c8,$c7,$c6,$c5,$c4,$00,$04
@env3:
	.byte $c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$00,$07
@env4:
	.byte $c4,$c3,$c2,$c2,$c1,$00,$04
@env5:
	.byte $c4,$c6,$c4,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$c0,$bc,$ba,$bc,$c0
	.byte $c4,$c6,$c4,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$c0,$bc,$ba,$bc,$c0
	.byte $c4,$c6,$c4,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$c0,$bc,$ba,$bc,$c0
	.byte $c4,$c6,$c4,$c0,$bc,$ba,$bc,$c0,$c4,$c6,$c4,$c0,$bc,$ba,$bc,$c0
	.byte $00,$3f
@env6:
	.byte $c2,$c3,$c2,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$c0
	.byte $c2,$c3,$c2,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$c0
	.byte $c2,$c3,$c2,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$c0
	.byte $c2,$c3,$c2,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$c0
	.byte $00,$3f
@env7:
	.byte $c0,$08,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c8,$c9,$ca,$cb,$cc,$cd,$ce
	.byte $cf,$0a,$cd,$c9,$c5,$c3,$c1,$0c,$c1,$00,$18


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $86,$1a,$8d,$18,$8d,$1a,$8d,$18,$8d
@ref1:
	.byte $1a,$8d,$18,$8d,$1a,$8d,$18,$8d
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $ff,$08
	.word @ref1
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref14:
	.byte $8a,$32,$85,$00,$85,$22,$85,$00,$85,$32,$85,$00,$85,$22,$85,$00
	.byte $85
@ref15:
	.byte $32,$85,$00,$85,$22,$85,$00,$85,$32,$85,$00,$85,$22,$85,$00,$85
@ref16:
	.byte $82,$32,$00,$33,$31,$88,$36,$89,$82,$33,$37,$3a,$00,$3b,$37,$88
	.byte $3a,$91
@ref17:
	.byte $82,$32,$00,$33,$31,$88,$36,$89,$82,$33,$37,$3a,$00,$3b,$37,$88
	.byte $41,$01,$3b,$36,$85
	.byte $ff,$0e
	.word @ref16
	.byte $ff,$11
	.word @ref17
	.byte $ff,$0e
	.word @ref16
	.byte $ff,$11
	.word @ref17
	.byte $ff,$0e
	.word @ref16
	.byte $ff,$11
	.word @ref17
@ref24:
	.byte $84,$4a,$00,$4b,$49,$82,$4f,$88,$4e,$85,$84,$4b,$4f,$52,$00,$53
	.byte $4f,$82,$53,$88,$52,$8d
@ref25:
	.byte $84,$4a,$00,$4b,$49,$82,$4f,$88,$4e,$85,$84,$4b,$4f,$52,$00,$53
	.byte $4f,$82,$59,$01,$84,$53,$4e,$85
@ref26:
	.byte $4a,$00,$4b,$49,$82,$4f,$88,$4e,$85,$84,$4b,$4f,$52,$00,$53,$4f
	.byte $82,$53,$88,$52,$8d
	.byte $ff,$12
	.word @ref25
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref28:
	.byte $00,$bd
@ref29:
	.byte $bf
@ref30:
	.byte $00,$bd
@ref31:
	.byte $bf
@ref32:
	.byte $00,$bd
@ref33:
	.byte $bf
@ref34:
	.byte $8a,$33,$3b,$41,$33,$3b,$41,$33,$3b,$41,$33,$3b,$40,$85,$37,$3b
	.byte $36,$81
@ref35:
	.byte $33,$3b,$41,$33,$3b,$41,$33,$3b,$41,$33,$3b,$40,$85,$37,$3b,$36
	.byte $81
	.byte $ff,$11
	.word @ref35
	.byte $ff,$11
	.word @ref35
@ref38:
	.byte $3a,$83,$00,$8f,$36,$83,$00,$3a,$83,$00,$8f,$36,$83,$00
@ref39:
	.byte $3a,$83,$00,$8f,$36,$83,$00,$40,$83,$00,$83,$3b,$01,$37,$3b,$36
	.byte $81
	.byte $ff,$0e
	.word @ref38
	.byte $ff,$11
	.word @ref39
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref42:
	.byte $8a,$20,$85,$12,$85,$20,$85,$12,$85,$20,$85,$12,$85,$20,$85,$13
	.byte $00,$81
@ref43:
	.byte $20,$85,$12,$85,$20,$85,$12,$85,$20,$85,$12,$85,$20,$85,$13,$00
	.byte $81
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $ff,$11
	.word @ref43
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref56:
	.byte $bf
@ref57:
	.byte $bf
@ref58:
	.byte $bf
@ref59:
	.byte $bf
@ref60:
	.byte $bf
@ref61:
	.byte $bf
@ref62:
	.byte $bf
@ref63:
	.byte $bf
@ref64:
	.byte $bf
@ref65:
	.byte $bf
@ref66:
	.byte $bf
@ref67:
	.byte $bf
@ref68:
	.byte $bf
@ref69:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$05
@song1ch0loop:
@ref70:
	.byte $82,$1b,$01,$1b,$1f,$23,$01,$8a,$23,$01,$82,$23,$01,$8a,$23,$01
	.byte $82,$23,$01,$8a,$23,$01,$82,$1b,$01,$8a,$1b,$1f,$23,$01,$86,$33
	.byte $01,$8a,$23,$01,$86,$33,$01,$8a,$23,$01,$86,$33,$00,$81
	.byte $ff,$21
	.word @ref70
	.byte $ff,$21
	.word @ref70
	.byte $ff,$21
	.word @ref70
	.byte $ff,$21
	.word @ref70
	.byte $ff,$21
	.word @ref70
	.byte $ff,$21
	.word @ref70
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref77:
	.byte $83,$86,$1b,$01,$1b,$1f,$23,$01,$8a,$23,$01,$86,$23,$01,$8a,$23
	.byte $01,$86,$23,$01,$8a,$23,$01,$86,$1b,$01,$8a,$1b,$1f,$23,$01,$33
	.byte $01,$23,$01,$33,$01,$23,$01,$32,$81
	.byte $ff,$21
	.word @ref77
	.byte $ff,$21
	.word @ref77
	.byte $ff,$21
	.word @ref77
	.byte $ff,$21
	.word @ref77
	.byte $ff,$21
	.word @ref77
	.byte $ff,$21
	.word @ref77
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref84:
	.byte $00,$f9,$83
@ref85:
	.byte $00,$f9,$83
@ref86:
	.byte $84,$62,$95,$88,$62,$89,$84,$63,$5c,$85,$58,$89,$53,$62,$95,$88
	.byte $62,$89,$84,$63,$5c,$85,$58,$89,$52,$81
@ref87:
	.byte $54,$95,$88,$54,$89,$84,$55,$52,$85,$54,$85,$01,$53,$54,$95,$88
	.byte $54,$89,$84,$55,$52,$85,$54,$85,$01,$52,$81
@ref88:
	.byte $62,$95,$88,$62,$89,$84,$63,$5c,$85,$58,$89,$53,$62,$95,$88,$62
	.byte $89,$84,$63,$5c,$85,$58,$89,$52,$81
@ref89:
	.byte $53,$55,$58,$8d,$88,$58,$8b,$00,$84,$58,$85,$54,$85,$53,$01,$53
	.byte $55,$58,$8d,$88,$58,$8b,$00,$84,$58,$85,$54,$85,$52,$85
@ref90:
	.byte $88,$62,$8d,$62,$8d,$84,$62,$85,$5c,$85,$58,$85,$52,$85,$88,$52
	.byte $8d,$4e,$8d,$84,$4a,$8d,$88,$4a,$8d
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref91:
	.byte $f9,$85
@ref92:
	.byte $f9,$85
@ref93:
	.byte $f9,$85
@ref94:
	.byte $f9,$85
@ref95:
	.byte $f9,$85
@ref96:
	.byte $f9,$85
@ref97:
	.byte $f9,$85
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref98:
	.byte $f9,$85
@ref99:
	.byte $f9,$85
@ref100:
	.byte $f9,$85
@ref101:
	.byte $f9,$85
@ref102:
	.byte $f9,$85
@ref103:
	.byte $f9,$85
@ref104:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@ref105:
	.byte $84,$40,$3c,$40,$85,$00,$f1
@song2ch0loop:
@ref106:
	.byte $a1
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref107:
	.byte $83,$8a,$40,$3c,$40,$85,$00,$ed
@song2ch1loop:
@ref108:
	.byte $a1
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref109:
	.byte $f9,$85
@song2ch2loop:
@ref110:
	.byte $a1
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref111:
	.byte $f9,$85
@song2ch3loop:
@ref112:
	.byte $a1
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref113:
	.byte $f9,$85
@song2ch4loop:
@ref114:
	.byte $a1
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@ref115:
	.byte $f9,$85
@song3ch0loop:
@ref116:
	.byte $a1
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref117:
	.byte $f9,$85
@song3ch1loop:
@ref118:
	.byte $a1
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref119:
	.byte $8a,$2e,$85,$2a,$85,$28,$85,$2a,$85,$8c,$2a,$9d,$00,$bd
@song3ch2loop:
@ref120:
	.byte $a1
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref121:
	.byte $f9,$85
@song3ch3loop:
@ref122:
	.byte $a1
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref123:
	.byte $f9,$85
@song3ch4loop:
@ref124:
	.byte $a1
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$06
@song4ch0loop:
@ref125:
	.byte $80,$33,$01,$33,$40,$91,$01,$41,$3c,$85,$41,$3a,$99,$32,$00,$33
	.byte $01,$33,$3c,$89,$3d,$3b,$3d,$36,$85
@ref126:
	.byte $01,$3b,$37,$3b,$32,$9d,$33,$01,$33,$40,$91,$01,$41,$3c,$85,$41
	.byte $3a,$99
@ref127:
	.byte $32,$00,$33,$01,$33,$3c,$89,$3d,$3b,$3d,$36,$85,$01,$3b,$37,$3b
	.byte $32,$9f
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref128:
	.byte $00,$f9,$83
@ref129:
	.byte $bb,$82,$48,$95,$4a,$89,$01,$40,$99
@ref130:
	.byte $8f,$44,$91,$01,$3c,$89,$3a,$89,$3a,$95,$84,$58,$85,$00
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref131:
	.byte $00,$89,$80,$32,$91,$01,$32,$85,$01,$32,$99,$00,$91,$3c,$9d
@ref132:
	.byte $8f,$32,$9d,$00,$89,$32,$91,$01,$32,$85,$01,$32,$99,$00,$81
@ref133:
	.byte $8f,$3c,$ad,$32,$9f
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref134:
	.byte $f9,$85
@ref135:
	.byte $f9,$85
@ref136:
	.byte $e1
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref137:
	.byte $f9,$85
@ref138:
	.byte $f9,$85
@ref139:
	.byte $e1
	.byte $fd
	.word @song4ch4loop
